### ISSUE TITLE
Add specs for invalid cases

### ISSUE THREAD

**Issue by soumyaray** [soumyaray/citesight#8]
examples:
- fragment: Ray et al (2000) et al.
- year with no parens: In 2010, several papers claimed that...

**Comment by wbw20** [comment]
:+1:

**Comment by soumyaray** [comment]
@wbw20, could you tell me a bit more about how you are using this gem?  I'm planning to work on this gem more actively soon, and I'd like to know a bit more about features would be helpful to folks.  btw, a very basic (for now) web interface to the gem is available at: inciteful.herokuapp.com
